### ISSUE TITLE
How to get access to the breast biopsy dataset?

### ISSUE THREAD

**Issue by alibalapour** [sacmehta/HATNet#2]
Hello.
I want to test your model, but I can't find the dataset (The breast biopsy dataset) you mentioned and investigated in the paper. Can you provide a direct link to the dataset or suggest a way to get the dataset? 
Thanks

**Comment by bushra-tayyaba** [comment]
Hello, 
I have the same query regarding the dataset. Have to manage to download the dataset in any way? kindly let me know too.

**Comment by sacmehta** [comment]
Dataset is private and can’t be open-sourced because of patient privacy issues.

**Comment by alibalapour** [comment]
> 

Hello,
I couldn't download the breast biopsy dataset, but I used Camelyon16 instead.

**Comment by alibalapour** [comment]
> Hello, I have the same query regarding the dataset. Have to manage to download the dataset in any way? kindly let me know too.

Hello,
I couldn't download the dataset, but I used Camelyon16 instead.

**Comment by bushra-tayyaba** [comment]
> > Hello, I have the same query regarding the dataset. Have to manage to download the dataset in any way? kindly let me know too.
> 
> Hello, I couldn't download the dataset, but I used Camelyon16 instead.

What necessary changes were made overall for this dataset.

**Comment by alibalapour** [comment]
> > > Hello, I have the same query regarding the dataset. Have to manage to download the dataset in any way? kindly let me know too.
> > 
> > 
> > Hello, I couldn't download the dataset, but I used Camelyon16 instead.
> 
> What necessary changes were made overall for this dataset.

First of all, you should fine-tune HATNet on the training set of Camelyon to convert the 4-class classifier to a 2-class classifier. After that, you can use the model. Also, you can use the feature generated in the layer before the classifier layer.
Please note that you should use the level 6 zoom setting on the WSIs of CAMELYON.

**Comment by yektaalavi** [comment]
> > > > Hello, I have the same query regarding the dataset. Have to manage to download the dataset in any way? kindly let me know too.
> > > 
> > > 
> > > Hello, I couldn't download the dataset, but I used Camelyon16 instead.
> > 
> > 
> > What necessary changes were made overall for this dataset.
> 
> First of all, you should fine-tune HATNet on the training set of Camelyon to convert the 4-class classifier to a 2-class classifier. After that, you can use the model. Also, you can use the feature generated in the layer before the classifier layer. Please note that you should use the level 6 zoom setting on the WSIs of CAMELYON.



Hello Ali,
How can I get access to Camelyon16 Dataset?
I have sent several access requests for their google drive storage but they did not do anything,
can I contact you via this email address for some asking some questions about this task and Camelyon?
yektaalavi15@gmail.com

**Comment by alibalapour** [comment]
> > > > > Hello, I have the same query regarding the dataset. Have to manage to download the dataset in any way? kindly let me know too.
> > > > 
> > > > 
> > > > Hello, I couldn't download the dataset, but I used Camelyon16 instead.
> > > 
> > > 
> > > What necessary changes were made overall for this dataset.
> > 
> > 
> > First of all, you should fine-tune HATNet on the training set of Camelyon to convert the 4-class classifier to a 2-class classifier. After that, you can use the model. Also, you can use the feature generated in the layer before the classifier layer. Please note that you should use the level 6 zoom setting on the WSIs of CAMELYON.
> 
> Hello Ali, How can I get access to Camelyon16 Dataset? I have sent several access requests for their google drive storage but they did not do anything, can I contact you via this email address for some asking some questions about this task and Camelyon? [yektaalavi15@gmail.com](mailto:yektaalavi15@gmail.com)

Hello.
To get access to the Camelyon16 dataset, you can check this link: [00-download-slides - Databricks](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/1839019694868427/63194501763100/1720491171398644/latest.html)
Yes. Feel free to contact me about this task and related datasets. My e-mail: alibalapour93.ab@gmail.com
